defaults:
  - _self_
  - trainer: lightning
  - logger: default_logger
  - callbacks: default_callbacks

  - system: none
  - launcher: local
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

model_name: "base"
test: false
print_conf: true

seed: 0
num_workers: 4
batch_size: 32
base_batch_size: ${batch_size} # to scale learning rate
resume: false
ckpt: null

train_transform: null
val_transform: null
test_transform: ${val_transform}

nodes: 1
gpus: 1

debug: false

hydra:
  run:
    dir: .
  output_subdir: null
